# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b375e09dbf8bc8fba56b050a88f477683179164eefb555a3a0a29b398b895116a72b461ee7e9eec3a29e5f1d118cccd7ecaf3f652ff7e54c3de0153df49b8cad

test:
  secret_key_base: bba3883b40ecbfaa341038b458dc8373e97e9483f123fd858561a5a004767410886f81f0f1154cb2362884f283bc29de54c73ee3e3a9ad608743b42751c421ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
